-- MariaDB dump 10.19  Distrib 10.11.4-MariaDB, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: wshop_api_store
-- ------------------------------------------------------
-- Server version	10.11.4-MariaDB-1~deb12u1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`wshop_api_store` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `wshop_api_store`;
--
-- Table structure for table `shops`
--

DROP TABLE IF EXISTS `shops`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `shops` (
  `shop_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `shop_name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `shop_description` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `shop_address` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `shop_phone` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `shop_email` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `shop_website` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  PRIMARY KEY (`shop_id`)
) ENGINE=InnoDB AUTO_INCREMENT=610 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `shops`
--

LOCK TABLES `shops` WRITE;
/*!40000 ALTER TABLE `shops` DISABLE KEYS */;
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Skimia', 'Pellentesque at nulla.', '91083 Grayhawk Pass', '+86 776 983 6453', 'csalmoni0@blogtalkradio.com', 'uiuc.edu');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Brainverse', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '2987 Weeping Birch Crossing', '+48 170 149 6648', 'lpaddingdon1@nature.com', 'shareasale.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Jazzy', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '742 Waubesa Crossing', '+58 870 104 1230', 'spurchall2@so-net.ne.jp', 'usnews.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Topiczoom', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '7 Bayside Lane', '+351 996 613 8369', 'hcamilletti3@livejournal.com', 'scribd.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Demizz', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '58760 Garrison Crossing', '+55 984 215 5581', 'blinzee4@hibu.com', 'bravesites.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Fliptune', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '13396 Ryan Avenue', '+234 417 184 3995', 'utrusse5@mapy.cz', 'toplist.cz');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Youfeed', 'Aliquam erat volutpat. In congue.', '84650 Lien Crossing', '+62 901 411 1529', 'tassard6@google.com.br', 'pinterest.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Divape', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', '0 Prairieview Road', '+86 131 522 1963', 'jdooley7@topsy.com', 'blog.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Gabvine', 'Donec vitae nisi.', '525 Nobel Crossing', '+86 305 591 4813', 'bmay8@disqus.com', 'google.com.br');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Oyoyo', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', '88 Jana Drive', '+7 184 523 6809', 'ldalessandro9@buzzfeed.com', 'salon.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Thoughtworks', 'In hac habitasse platea dictumst.', '7 Surrey Road', '+374 355 618 7028', 'vheldera@miibeian.gov.cn', 'answers.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Fivebridge', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', '03 Pankratz Lane', '+86 940 615 7842', 'oproudmanb@symantec.com', 'freewebs.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Midel', 'Etiam vel augue.', '06135 Sunfield Trail', '+237 483 465 3666', 'okettc@yahoo.co.jp', 'uol.com.br');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Centimia', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '31624 Messerschmidt Plaza', '+351 796 110 0525', 'obucknalld@cocolog-nifty.com', 'reddit.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Twiyo', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '77 Spenser Alley', '+62 865 461 7995', 'glatche@geocities.jp', 'aol.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Blognation', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', '53242 Pine View Terrace', '+54 372 658 6565', 'lgeneverf@walmart.com', 'tinyurl.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Babbleset', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '0 Graceland Lane', '+63 392 976 1043', 'cedong@360.cn', 'un.org');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Jetwire', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '0 Iowa Trail', '+381 587 975 9820', 'bpascoeh@macromedia.com', 'disqus.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Edgepulse', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', '93888 Coleman Road', '+81 672 106 6820', 'zfollani@state.gov', 'list-manage.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Camimbo', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '6974 Northwestern Hill', '+86 119 363 5716', 'arandellj@tiny.cc', 'behance.net');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Jetwire', 'Morbi quis tortor id nulla ultrices aliquet.', '31 Sachtjen Pass', '+81 484 868 9985', 'tsharplyk@seattletimes.com', 'creativecommons.org');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Centizu', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', '9249 Hoepker Avenue', '+33 793 999 3156', 'drispinel@hatena.ne.jp', 'tiny.cc');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Thoughtblab', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', '1 Kensington Avenue', '+359 357 927 2382', 'sfeasleym@ucsd.edu', 'bravesites.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Skipstorm', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '79 Bunker Hill Avenue', '+237 308 330 2093', 'jygoun@twitter.com', 'free.fr');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Feedfire', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '811 Gateway Park', '+86 445 302 0248', 'fgreggso@toplist.cz', '51.la');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Flashset', 'In hac habitasse platea dictumst.', '38 Pankratz Pass', '+86 531 599 9525', 'edyneleyp@vistaprint.com', 'auda.org.au');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Rhybox', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '77 Moulton Lane', '+263 417 747 4893', 'jcotgroveq@sakura.ne.jp', 'hubpages.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Jaxspan', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '382 Bunker Hill Plaza', '+86 921 398 5494', 'achaucerr@stanford.edu', 'google.co.uk');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Eadel', 'Etiam faucibus cursus urna. Ut tellus.', '79273 Gerald Pass', '+970 666 512 4425', 'wdimitrious@nbcnews.com', 'wikispaces.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Demizz', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '6516 Pepper Wood Court', '+86 851 859 3889', 'mbiggt@scientificamerican.com', 'github.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Muxo', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '789 Carpenter Junction', '+261 747 362 1493', 'smandyu@bloomberg.com', 'mac.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Jetwire', 'Pellentesque viverra pede ac diam.', '8107 Mallory Drive', '+31 596 776 2918', 'owolpertv@miitbeian.gov.cn', 'printfriendly.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Tagopia', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '136 Longview Place', '+58 726 709 8142', 'blanganw@accuweather.com', 'who.int');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Vinte', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '2 La Follette Plaza', '+86 855 688 2338', 'hambridgex@privacy.gov.au', 'marriott.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Oodoo', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '59529 Namekagon Avenue', '+48 275 588 6980', 'tdcruzey@netscape.com', 'meetup.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Abatz', 'Quisque ut erat. Curabitur gravida nisi at nibh.', '99877 Esker Street', '+63 355 350 6054', 'vhegdonnez@photobucket.com', 'buzzfeed.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Vitz', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '30 Canary Junction', '+86 127 321 4427', 'lramsted10@ovh.net', 'usda.gov');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Browseblab', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', '629 Comanche Street', '+62 751 600 1728', 'mvonoertzen11@slashdot.org', 'webnode.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Photobug', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '8966 Norway Maple Place', '+48 327 741 3240', 'amarco12@home.pl', 'who.int');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Omba', 'Aliquam non mauris. Morbi non lectus.', '17204 Hoffman Alley', '+52 262 202 7043', 'afenby13@whitehouse.gov', 'constantcontact.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Meevee', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '270 Hanover Crossing', '+7 840 954 6602', 'acolqueran14@over-blog.com', 'nasa.gov');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Rooxo', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', '6178 Sherman Terrace', '+54 859 339 4172', 'edomnick15@loc.gov', 'google.nl');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Gigashots', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '841 Florence Circle', '+63 109 183 7102', 'llaise16@rediff.com', 'domainmarket.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Flashdog', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', '41 Nancy Drive', '+62 748 842 6555', 'cballance17@studiopress.com', 'cisco.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Kwinu', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '1892 Debs Trail', '+351 955 524 6395', 'hgartin18@mozilla.com', 'shutterfly.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Meemm', 'Praesent blandit.', '1 South Parkway', '+52 334 993 9855', 'dswett19@google.ru', 'google.com.hk');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Jamia', 'Vestibulum ac est lacinia nisi venenatis tristique.', '31560 Division Drive', '+251 444 599 7813', 'kbroadbury1a@mozilla.com', 'hibu.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Flipstorm', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', '599 Troy Pass', '+98 982 410 9619', 'fmatyushenko1b@stanford.edu', 'ovh.net');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Kwinu', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', '51 Boyd Avenue', '+81 473 749 6238', 'rtothacot1c@discuz.net', 'who.int');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Skippad', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '7 Helena Circle', '+502 934 396 9706', 'mbarbery1d@icq.com', 'skyrock.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Photolist', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '3 Valley Edge Junction', '+62 167 590 8047', 'ldymond1e@xinhuanet.com', 'redcross.org');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Zoozzy', 'Nulla ac enim.', '0 Prentice Way', '+86 933 239 4496', 'jlamyman1f@bloomberg.com', 'google.es');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Wordtune', 'Vivamus in felis eu sapien cursus vestibulum.', '582 Evergreen Street', '+48 217 902 8464', 'bteenan1g@columbia.edu', 'elpais.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Shufflebeat', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '860 Tennyson Terrace', '+93 836 262 7748', 'bblood1h@4shared.com', 'mit.edu');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Photofeed', 'Morbi quis tortor id nulla ultrices aliquet.', '5 Lake View Junction', '+1 615 426 2675', 'lwarman1i@usnews.com', 'time.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Flipbug', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '50 Weeping Birch Street', '+62 894 255 6985', 'tlongrigg1j@netlog.com', 'unblog.fr');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Skynoodle', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', '5426 Hayes Center', '+33 910 746 4011', 'sfreschini1k@nps.gov', 'google.pl');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Oyondu', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '886 Shoshone Court', '+33 594 417 6928', 'dbare1l@economist.com', 'digg.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Zoomdog', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '7 Weeping Birch Parkway', '+960 349 229 1182', 'fpain1m@about.me', 'php.net');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Skyndu', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '57 Mallard Center', '+62 416 138 9513', 'zmeneghi1n@furl.net', 'g.co');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Kazio', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2 Crowley Circle', '+55 331 916 0380', 'zlabat1o@homestead.com', 'edublogs.org');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Bluejam', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', '09 Pepper Wood Parkway', '+46 471 413 1131', 'lpeace1p@webnode.com', 'walmart.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Realbridge', 'Praesent blandit.', '546 Ridgeway Trail', '+45 749 829 1476', 'eneeves1q@spiegel.de', 'usda.gov');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Eadel', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '0795 Rieder Point', '+86 759 927 6161', 'mlepper1r@rediff.com', 'devhub.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Zoomcast', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', '60 Sachs Place', '+62 874 772 4047', 'asterke1s@amazon.co.uk', 'slashdot.org');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Eabox', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '94505 Holmberg Avenue', '+92 571 430 3290', 'nbonaire1t@bizjournals.com', 'cdbaby.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Mita', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', '26284 Corry Circle', '+7 268 633 7411', 'fmarchetti1u@webs.com', 'blog.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Rhycero', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '409 Kingsford Drive', '+351 866 117 1022', 'npuden1v@webs.com', 'ucoz.ru');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Npath', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '73 Surrey Avenue', '+48 678 942 0068', 'mnatwick1w@mapquest.com', 'youtube.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Kimia', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', '3 Darwin Center', '+967 487 881 3099', 'obaldung1x@yale.edu', 'wordpress.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Lajo', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', '29273 Namekagon Way', '+63 722 872 2595', 'jdrinkhill1y@blogs.com', 'bloomberg.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Aibox', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', '9886 Northland Circle', '+267 338 799 9947', 'sstainsby1z@icio.us', 'flavors.me');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Jabberstorm', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '3217 Cascade Drive', '+352 289 931 0749', 'vtieman20@businessweek.com', 'scribd.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Yodo', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', '458 Delaware Street', '+86 860 102 5771', 'joconcannon21@rediff.com', 'odnoklassniki.ru');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Quimm', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '6689 Larry Plaza', '+63 445 582 7101', 'emaffezzoli22@bigcartel.com', 'ca.gov');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Photobug', 'Suspendisse accumsan tortor quis turpis. Sed ante.', '60378 Marquette Court', '+1 213 130 3706', 'lloudiane23@cargocollective.com', 'example.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Agimba', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '31130 Porter Junction', '+55 663 163 7489', 'rgreenly24@indiatimes.com', 'tuttocitta.it');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Skynoodle', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '867 Holy Cross Trail', '+234 899 856 9442', 'seisak25@irs.gov', 'hao123.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Blognation', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', '062 Bunker Hill Way', '+63 392 967 3938', 'jkincade26@gizmodo.com', 'bravesites.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Topicware', 'Nam nulla.', '4940 Schurz Court', '+86 217 290 5347', 'agowdy27@simplemachines.org', 'youtube.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Browsetype', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '34 Duke Terrace', '+57 940 254 1254', 'pdayes28@jalbum.net', 'theglobeandmail.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Innotype', 'Aliquam quis turpis eget elit sodales scelerisque.', '166 Gulseth Pass', '+509 650 530 2527', 'aemeney29@huffingtonpost.com', 'furl.net');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Vimbo', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '80 Iowa Circle', '+86 422 442 7477', 'kskep2a@walmart.com', 'loc.gov');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Shufflebeat', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', '82 Londonderry Alley', '+55 606 954 2385', 'rhubbart2b@engadget.com', 'google.fr');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Zoomlounge', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '084 East Street', '+48 805 685 9452', 'eabrahim2c@sakura.ne.jp', 'netscape.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Jetwire', 'Donec quis orci eget orci vehicula condimentum.', '068 Spenser Lane', '+46 674 629 0947', 'skail2d@geocities.com', 'lulu.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Realcube', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '32 Doe Crossing Road', '+63 306 109 7809', 'gmatterface2e@clickbank.net', 'naver.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Latz', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', '29993 Onsgard Junction', '+55 147 182 1237', 'dvise2f@csmonitor.com', 'microsoft.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Ntags', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '94537 Gale Pass', '+86 651 469 3121', 'acarney2g@shareasale.com', 'sohu.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Vinte', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '698 Jenna Road', '+81 175 713 4028', 'ecuzen2h@bluehost.com', 'plala.or.jp');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Quimba', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '16 Duke Hill', '+86 541 669 9949', 'bfatscher2i@scientificamerican.com', 'spotify.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Dablist', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '04703 Bellgrove Plaza', '+86 321 910 3846', 'mdobel2j@ihg.com', 'si.edu');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Photobug', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '6166 Canary Parkway', '+55 385 623 8924', 'mlampert2k@jugem.jp', 'phpbb.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Snaptags', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '05 Lotheville Court', '+30 249 496 2975', 'epencost2l@slate.com', 'auda.org.au');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Oyoba', 'Duis ac nibh.', '5074 Boyd Pass', '+46 289 734 1638', 'handreoletti2m@yale.edu', 'weebly.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Innotype', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '05 Hollow Ridge Crossing', '+86 444 683 2780', 'drochford2n@dot.gov', 'usatoday.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Wordpedia', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', '16 Little Fleur Crossing', '+62 376 263 2714', 'dswalowe2o@dropbox.com', 'si.edu');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Vidoo', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '5 David Street', '+33 396 407 8018', 'bdavidowsky2p@topsy.com', 'apple.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Browsecat', 'Integer ac leo.', '062 Manufacturers Street', '+86 560 194 5432', 'nfortye2q@nifty.com', 'sphinn.com');
INSERT INTO shops (shop_name, shop_description, shop_address, shop_phone, shop_email, shop_website) VALUES ('Leenti', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '6 Hermina Center', '+48 667 603 3954', 'oherreros2r@google.co.jp', 'google.ca');
/*!40000 ALTER TABLE `shops` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2023-11-07 22:20:10
